server:
  port: 8761
  compression:
    enabled: true

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  server:
    # see discussion about enable-self-preservation:
    # https://github.com/jhipster/generator-jhipster/issues/3654
    enable-self-preservation: false
    peer-node-read-timeout-ms: 3000
